/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_peminjamanalat;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author windows10
 */
public class fAdministrator extends javax.swing.JFrame {

    DefaultTableModel masuk, keluar, masuk1, keluar1;
    koneksi konek = new koneksi();
    /**
     * Creates new form fUser
     */
    public fAdministrator() {
        
        konek.koneksi();
        initComponents();
        
        
        btnTambah.setBackground(Color.red);
        btnEdit.setBackground(Color.blue);
        btnDelete.setBackground(Color.green);
        btnHapus.setBackground(Color.green);
        btnKeluar.setBackground(Color.yellow);
        btnCari.setBackground(Color.red);
        btnExcel.setBackground(Color.blue);
        btnPdf.setBackground(Color.yellow);
       
       
        tampil_masuk();
        tampil_keluar();
        tampil_masuk1();
        tampil_keluar1();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        txtKID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_keluar = new javax.swing.JTable();
        btnExcel = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_masuk = new javax.swing.JTable();
        txtPass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnCari1 = new javax.swing.JButton();
        txtKID1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_keluar1 = new javax.swing.JTable();
        btnExcel1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnPdf1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnEdit1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnTambah1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        txtNama1 = new javax.swing.JTextField();
        txtTelp1 = new javax.swing.JTextField();
        btnKeluar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAlamat1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabel_masuk1 = new javax.swing.JTable();
        txtPass1 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnTutup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel7.setText("ID / Nama");

        tabel_keluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "No. Telp", "Alamat", "E-mail"
            }
        ));
        jScrollPane3.setViewportView(tabel_keluar);

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExcel.setText("Save to Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon (1).png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        btnPdf.setText("Save to Pdf");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPdf)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Informasi Toolman", jPanel2);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon.png"))); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon.png"))); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-icon.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Toolman");

        jLabel3.setText("Nama ");

        jLabel4.setText("No. Telepon");

        jLabel5.setText("Alamat");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close-2-icon.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        jLabel6.setText("Password ");

        tabel_masuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Telp", "Alamat", "Password", "E-mail"
            }
        ));
        tabel_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_masukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabel_masukMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_masuk);

        jLabel8.setText("E-mail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelp)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPass)
                                    .addComponent(txtEmail))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Toolman", jPanel1);

        btnCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnCari1.setText("Cari");
        btnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari1ActionPerformed(evt);
            }
        });

        jLabel9.setText("ID / Nama");

        tabel_keluar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "No. Telp", "Alamat", "E-mail"
            }
        ));
        jScrollPane4.setViewportView(tabel_keluar1);

        btnExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExcel1.setText("Save to Excel");
        btnExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel1ActionPerformed(evt);
            }
        });

        btnHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon (1).png"))); // NOI18N
        btnHapus1.setText("Hapus");
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        btnPdf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        btnPdf1.setText("Save to Pdf");
        btnPdf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdf1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKID1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPdf1)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPdf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Informasi Admin", jPanel3);

        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon.png"))); // NOI18N
        btnEdit1.setText("Ubah");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon.png"))); // NOI18N
        btnDelete1.setText("Hapus");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-icon.png"))); // NOI18N
        btnTambah1.setText("Tambah");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID Admin");

        jLabel11.setText("Nama ");

        jLabel12.setText("No. Telepon");

        jLabel13.setText("Alamat");

        txtID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtID1KeyTyped(evt);
            }
        });

        txtTelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelp1ActionPerformed(evt);
            }
        });

        btnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close-2-icon.png"))); // NOI18N
        btnKeluar1.setText("Keluar");
        btnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar1ActionPerformed(evt);
            }
        });

        txtAlamat1.setColumns(20);
        txtAlamat1.setRows(5);
        jScrollPane5.setViewportView(txtAlamat1);

        jLabel14.setText("Password ");

        tabel_masuk1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Telp", "Alamat", "Password", "E-mail"
            }
        ));
        tabel_masuk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_masuk1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabel_masuk1MouseEntered(evt);
            }
        });
        jScrollPane6.setViewportView(tabel_masuk1);

        jLabel15.setText("E-mail");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelp1)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnKeluar1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPass1)
                                    .addComponent(txtEmail1))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Daftar Administrator", jPanel4);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA INFORMASI TOOLMAN / ADMIN");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jMenu1.setText("Data Toolman/ Admin");

        mnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-48.png"))); // NOI18N
        mnTutup.setText("Tutup");
        mnTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnTutupMousePressed(evt);
            }
        });
        jMenu1.add(mnTutup);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTutupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTutupMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnTutupMousePressed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID belum diisi!");
        } else if (txtNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        } else if (txtTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomer Telepon belum diisi!");
        } else if (txtAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat belum diisi!");
        } else if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email belum diisi!");
        } else if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password Barang belum diisi!");
        } else {
            
            String id, nama, telepon, alamat, password, email, sql;
            
            id = txtID.getText();
            nama = txtNama.getText();
            telepon = txtTelp.getText();
            alamat = txtAlamat.getText();
            password = txtPass.getText();
            email = txtEmail.getText();
       
            sql = "INSERT INTO tb_toolman(id,username,no_telepon,alamat,password,email)"
                    + "VALUES('"+id+"','"+nama+"','"+telepon+"','"+alamat+"','"+password+"','"+email+"')";
           
            try { 
                konek.st = konek.conn.createStatement();
                konek.st.execute(sql);
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan"+e);
                return;
            }
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
        }
        
        resetAll();
        tampil_masuk();
        tampil_keluar();                
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
      
          int index = tabel_masuk.getSelectedRow();
          String sql;
          sql = "DELETE FROM tb_toolman WHERE id = '"+txtID.getText()+"'";
          masuk.removeRow(index);
          
          try {
              
              konek.st = konek.conn.createStatement();
              konek.st.execute(sql);
          }
          catch (SQLException e){
              JOptionPane.showMessageDialog(this, "Data gagal dihapus"+e);
              return;
          }
          JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID belum diisi!");
        } else if (txtNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        } else if (txtTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomer Telepon belum diisi!");
        } else if (txtAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat belum diisi!");
        } else if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email belum diisi!");
        } else if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password Barang belum diisi!");
        } else {
            
            
            String sql = "update tb_toolman set"
                    +" id = '"+txtID.getText()+"',"
                    +" username = '"+txtNama.getText()+"',"
                    +" no_telepon = '"+txtTelp.getText()+"',"
                    +" email = '"+txtEmail.getText()+"',"
                    +" alamat = '"+txtAlamat.getText()+"' where"
                    +" password = '"+txtPass.getText()+"'";
            
            try {
                
                konek.st = konek.conn.createStatement();
                konek.st.executeUpdate(sql);
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal diubah"+e);
                return; 
                }
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        }
        
        resetAll();
        tampil_masuk();
        tampil_keluar();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabel_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_masukMouseClicked
        // TODO add your handling code here:
        
        try {
            int row = tabel_masuk.rowAtPoint(evt.getPoint());

        String id = tabel_masuk.getValueAt(row, 0).toString();
        String nama = tabel_masuk.getValueAt(row, 1).toString();
        String telepon = tabel_masuk.getValueAt(row, 2).toString();
        String alamat = tabel_masuk.getValueAt(row, 3).toString();
        String password = tabel_masuk.getValueAt(row, 4).toString();
        String email = tabel_masuk.getValueAt(row, 5).toString();

            txtID.setText(String.valueOf(id));
            txtNama.setText(String.valueOf(nama));
            txtTelp.setText(String.valueOf(telepon));
            txtAlamat.setText(String.valueOf(alamat));
            txtPass.setText(String.valueOf(password));
            txtEmail.setText(String.valueOf(email));
        
            } catch (Exception e) {

        }
    }//GEN-LAST:event_tabel_masukMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
     
        keluar = (DefaultTableModel) tabel_keluar.getModel();
        try {
            
            konek.st = konek.conn.createStatement();
            String sql = "Select * from tb_toolman where id like '%"+txtKID.getText()+"%'"+
            "or username like '%"+txtKID.getText()+"%'";
            konek.rs = konek.st.executeQuery(sql);
            while (konek.rs.next()) {
                
                String id = konek.rs.getString("id");
                String nama = konek.rs.getString("username");
                String telepon = konek.rs.getString("no_telepon");
                String alamat = konek.rs.getString("alamat");
                String email = konek.rs.getString("email");
                
     
                String [] data = {id, nama, telepon, alamat, email};
                keluar.addRow(data);
            }
            
    } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
    }
            tabel_keluar.setModel(keluar);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        keluar = (DefaultTableModel) tabel_keluar.getModel();
        try {
         
         int index = tabel_keluar.getSelectedRow();
         keluar.removeRow(index);
         
        } catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null, ex);
        }
         
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        
        
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = tabel_keluar.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));
                // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                    fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
                }
                fileWriter.write("\n");
                // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                    for(int j=0; j < tModel.getColumnCount(); j++) {
                        fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
                    }
                    fileWriter.write("\n");
                }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        // TODO add your handling code here:
        
        try     {
                
                konek.st = konek.conn.createStatement();
                String query = "SELECT * FROM tb_toolman WHERE id like '%"+txtKID.getText()+"%'"+
                "or username like '%"+txtKID.getText()+"%'";
                konek.rs = konek.st.executeQuery(query);
     
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Data Toolman.pdf"));
                document.open();
                document.addTitle("DAFTAR TOOLMAN/ADMIN APLIKASI");
                document.add(new Paragraph("DAFTAR TOOLMAN/ADMIN APLIKASI"));
                document.add (new Paragraph(" "));
                PdfPTable table = new PdfPTable(6);
                PdfPCell c1 = new PdfPCell (new Phrase("ID"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c1);
                
                PdfPCell c2 = new PdfPCell (new Phrase("Nama"));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c2);
                
                PdfPCell c3 = new PdfPCell (new Phrase("No. Telepon"));
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c3);
                
                PdfPCell c4 = new PdfPCell (new Phrase("Alamat"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
                
                PdfPCell c5 = new PdfPCell (new Phrase("Password"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c5);
                
                PdfPCell c6 = new PdfPCell (new Phrase("Email"));
                c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c6);
             
                while (konek.rs.next()){
                    
                    try {
                        table.addCell(konek.rs.getString("id"));
                        table.addCell(konek.rs.getString("username"));
                        table.addCell(konek.rs.getString("no_telepon"));
                        table.addCell(konek.rs.getString("alamat"));
                        table.addCell(konek.rs.getString("password"));
                        table.addCell(konek.rs.getString("email"));
                    }
                    catch (Exception e) {
                    }
                }
                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan, Data tersimpan didalam project");
            } catch(Exception e){
        }
    }//GEN-LAST:event_btnPdfActionPerformed

    private void tabel_masukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_masukMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_masukMouseEntered

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        
    }//GEN-LAST:event_txtIDKeyTyped

    private void btnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari1ActionPerformed
        // TODO add your handling code here:
        
        keluar1 = (DefaultTableModel) tabel_keluar1.getModel();
        try {
            
            konek.st = konek.conn.createStatement();
            String sql = "Select * from tb_admin where id_admin like '%"+txtKID1.getText()+"%'"+
            "or nama_admin like '%"+txtKID1.getText()+"%'";
            konek.rs = konek.st.executeQuery(sql);
            while (konek.rs.next()) {
                
                String id = konek.rs.getString("id_admin");
                String nama = konek.rs.getString("nama_admin");
                String telepon = konek.rs.getString("no_telepon");
                String alamat = konek.rs.getString("alamat");
                String email = konek.rs.getString("email");
                
     
                String [] data = {id, nama, telepon, alamat, email};
                keluar1.addRow(data);
            }
            
    } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
    }
            tabel_keluar1.setModel(keluar1);
        
    }//GEN-LAST:event_btnCari1ActionPerformed

    private void btnExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel1ActionPerformed
        // TODO add your handling code here:
         FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = tabel_keluar1.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));
                // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                    fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
                }
                fileWriter.write("\n");
                // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                    for(int j=0; j < tModel.getColumnCount(); j++) {
                        fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
                    }
                    fileWriter.write("\n");
                }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnExcel1ActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        // TODO add your handling code here:
        
        keluar1 = (DefaultTableModel) tabel_keluar1.getModel();
        try {
         
         int index = tabel_keluar1.getSelectedRow();
         keluar1.removeRow(index);
         
        } catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnPdf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdf1ActionPerformed
        // TODO add your handling code here:
        
         try     {
                
                konek.st = konek.conn.createStatement();
                String query = "SELECT * FROM tb_admin WHERE id_admin like '%"+txtKID1.getText()+"%'"+
                "or nama_admin like '%"+txtKID1.getText()+"%'";
                konek.rs = konek.st.executeQuery(query);
     
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Data Admin.pdf"));
                document.open();
                document.addTitle("DAFTAR TOOLMAN/ADMIN APLIKASI");
                document.add(new Paragraph("DAFTAR TOOLMAN/ADMIN APLIKASI"));
                document.add (new Paragraph(" "));
                PdfPTable table = new PdfPTable(6);
                PdfPCell c1 = new PdfPCell (new Phrase("ID"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c1);
                
                PdfPCell c2 = new PdfPCell (new Phrase("Nama"));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c2);
                
                PdfPCell c3 = new PdfPCell (new Phrase("No. Telepon"));
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c3);
                
                PdfPCell c4 = new PdfPCell (new Phrase("Alamat"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
                
                PdfPCell c5 = new PdfPCell (new Phrase("Password"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c5);
                
                PdfPCell c6 = new PdfPCell (new Phrase("Email"));
                c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c6);
             
                while (konek.rs.next()){
                    try {
                        table.addCell(konek.rs.getString("id_admin"));
                        table.addCell(konek.rs.getString("nama_admin"));
                        table.addCell(konek.rs.getString("no_telepon"));
                        table.addCell(konek.rs.getString("alamat"));
                        table.addCell(konek.rs.getString("password"));
                        table.addCell(konek.rs.getString("email"));
                    }
                    catch (Exception e) {
                    }
                }
                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan, Data tersimpan didalam project");
                
            } catch(Exception e){
        }
    }//GEN-LAST:event_btnPdf1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        if (txtID1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID belum diisi!");
        } else if (txtNama1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        } else if (txtTelp1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomer Telepon belum diisi!");
        } else if (txtAlamat1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat belum diisi!");
        } else if (txtEmail1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email belum diisi!");
        } else if (txtPass1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password Barang belum diisi!");
        } else {
            
            String sql = "update tb_admin set"
                    +" id_admin = '"+txtID1.getText()+"',"
                    +" nama_admin = '"+txtNama1.getText()+"',"
                    +" no_telepon = '"+txtTelp1.getText()+"',"
                    +" email = '"+txtEmail1.getText()+"',"
                    +" alamat = '"+txtAlamat1.getText()+"' where"
                    +" password = '"+txtPass1.getText()+"'";
            
            try {
                
                konek.st = konek.conn.createStatement();
                konek.st.executeUpdate(sql);
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal diubah"+e);
                return; 
                }
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        }
        
        resetAll1();
        tampil_masuk1();
        tampil_keluar1();
        
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        
          int index = tabel_masuk1.getSelectedRow();
          String sql;
          sql = "DELETE FROM tb_admin WHERE id = '"+txtID1.getText()+"'";
          masuk1.removeRow(index);
          
          try {
              
              konek.st = konek.conn.createStatement();
              konek.st.execute(sql);
          }
          catch (SQLException e){
              JOptionPane.showMessageDialog(this, "Data gagal dihapus"+e);
              return;
          }
          JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
        if (txtID1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID belum diisi!");
        } else if (txtNama1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        } else if (txtTelp1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nomer Telepon belum diisi!");
        } else if (txtAlamat1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat belum diisi!");
        } else if (txtEmail1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email belum diisi!");
        } else if (txtPass1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password Barang belum diisi!");
        } else {
            
            String id, nama, telepon, alamat, password, email, sql;
            
            id = txtID1.getText();
            nama = txtNama1.getText();
            telepon = txtTelp1.getText();
            alamat = txtAlamat1.getText();
            password = txtPass1.getText();
            email = txtEmail1.getText();
       
            sql = "INSERT INTO tb_admin (id_admin,nama_admin,no_telepon,alamat,password,email)"
                    + "VALUES('"+id+"','"+nama+"','"+telepon+"','"+alamat+"','"+password+"','"+email+"')";
           
            try { 
                konek.st = konek.conn.createStatement();
                konek.st.execute(sql);
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan"+e);
                return;
            }
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
        }
        
        resetAll1();
        tampil_masuk1();
        tampil_keluar1();  
        
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void txtID1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1KeyTyped

    private void txtTelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelp1ActionPerformed

    private void btnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar1ActionPerformed
        // TODO add your handling code here:
         dispose();
        
    }//GEN-LAST:event_btnKeluar1ActionPerformed

    private void tabel_masuk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_masuk1MouseClicked
        // TODO add your handling code here:
        try {
            int row = tabel_masuk1.rowAtPoint(evt.getPoint());

        String id = tabel_masuk1.getValueAt(row, 0).toString();
        String nama = tabel_masuk1.getValueAt(row, 1).toString();
        String telepon = tabel_masuk1.getValueAt(row, 2).toString();
        String alamat = tabel_masuk1.getValueAt(row, 3).toString();
        String password = tabel_masuk1.getValueAt(row, 4).toString();
        String email = tabel_masuk1.getValueAt(row, 5).toString();

            txtID1.setText(String.valueOf(id));
            txtNama1.setText(String.valueOf(nama));
            txtTelp1.setText(String.valueOf(telepon));
            txtAlamat1.setText(String.valueOf(alamat));
            txtPass1.setText(String.valueOf(password));
            txtEmail1.setText(String.valueOf(email));
        
            } catch (Exception e) {

        }
        
    }//GEN-LAST:event_tabel_masuk1MouseClicked

    private void tabel_masuk1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_masuk1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_masuk1MouseEntered

     public void resetAll(){
        
        txtID.setText("");
        txtNama.setText("");
        txtTelp.setText("");
        txtPass.setText("");
        txtAlamat.setText("");
        txtEmail.setText("");
   
        masuk = (DefaultTableModel) tabel_masuk.getModel();
        keluar = (DefaultTableModel) tabel_keluar.getModel();
       
        int rowCount1 = masuk.getRowCount();
        int rowCount2 = keluar.getRowCount();
       //Remove rows one by one from the end of the table
        
        for (int i = rowCount1 - 1; i >= 0; i--) {
            masuk.removeRow(i);
        }
        for (int i = rowCount2 - 1; i >= 0; i--) {
            keluar.removeRow(i);
        }

     }
      public void resetAll1(){
        
        txtID1.setText("");
        txtNama1.setText("");
        txtTelp1.setText("");
        txtPass1.setText("");
        txtAlamat1.setText("");
        txtEmail1.setText("");
   
        masuk1 = (DefaultTableModel) tabel_masuk1.getModel();
        keluar1 = (DefaultTableModel) tabel_keluar1.getModel();
       
        int rowCount1 = masuk1.getRowCount();
        int rowCount2 = keluar1.getRowCount();
       //Remove rows one by one from the end of the table
        
        for (int i = rowCount1 - 1; i >= 0; i--) {
            masuk1.removeRow(i);
        }
        for (int i = rowCount2 - 1; i >= 0; i--) {
            keluar1.removeRow(i);
        }
     
     }
     
    public void tampil_masuk(){
        
        masuk = (DefaultTableModel) tabel_masuk.getModel();
        
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT * FROM tb_toolman";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                String id = konek.rs.getString("id");
                String nama = konek.rs.getString("username");
                String telepon = konek.rs.getString("no_telepon");
                String alamat = konek.rs.getString("alamat");
                String password = konek.rs.getString("password");
                String email = konek.rs.getString("email");
     
                String [] data = {id, nama, telepon, alamat, password, email};
                masuk.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tabel_masuk.setModel(masuk);
    }

       
    public void tampil_keluar(){

    }
    public void tampil_masuk1(){
        
        masuk1 = (DefaultTableModel) tabel_masuk1.getModel();
        
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT * FROM tb_admin";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                String id = konek.rs.getString("id_admin");
                String nama = konek.rs.getString("nama_admin");
                String telepon = konek.rs.getString("no_telepon");
                String alamat = konek.rs.getString("alamat");
                String password = konek.rs.getString("password");
                String email = konek.rs.getString("email");
     
                String [] data = {id, nama, telepon, alamat, password, email};
                masuk1.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tabel_masuk1.setModel(masuk1);

    }
    
    
    public void tampil_keluar1(){
        
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fAdministrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnExcel1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKeluar1;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnPdf1;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnTutup;
    private javax.swing.JTable tabel_keluar;
    private javax.swing.JTable tabel_keluar1;
    private javax.swing.JTable tabel_masuk;
    private javax.swing.JTable tabel_masuk1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextArea txtAlamat1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtKID;
    private javax.swing.JTextField txtKID1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTelp1;
    // End of variables declaration//GEN-END:variables
}
