/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_peminjamanalat;

import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Color;
import java.io.*;
import java.sql.SQLException;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class fLaporan extends javax.swing.JFrame {

    DefaultTableModel peminjaman, pengembalian;
    koneksi konek = new koneksi();
    public fLaporan() {
        
        konek.koneksi();
        initComponents();
        
        btnPrint.setBackground(Color.green);
        btnPdf.setBackground(Color.red);
        btnHapus.setBackground(Color.blue);
        btnDelete.setBackground(Color.yellow);
        btnExcel.setBackground(Color.yellow);
        btnCetak.setBackground(Color.red);
        btnPDF.setBackground(Color.green);
        btnXls.setBackground(Color.blue);
        
        tampil_pinjam();
        tampil_kembali();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pinjam = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_kembali = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        btnXls = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnTutup = new javax.swing.JMenuItem();

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print-48.png"))); // NOI18N
        jButton3.setText("Print");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Data Peminjaman Alat");

        tabel_pinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kelas", "Jurusan", "Nama B", "Jmlh B", "Jam Pinjm", "Tgl  Pinjm"
            }
        ));
        jScrollPane1.setViewportView(tabel_pinjam);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print-48.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        btnPdf.setText("Save to Pdf");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExcel.setText("Save to Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon (1).png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcel)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Peminjaman", jPanel2);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Data Pengembalian Alat");

        tabel_kembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama", "Kelas", "Jurusan", "Tgl Pinjam", "Tgl Kmbli", "Jam Kmbli"
            }
        ));
        jScrollPane2.setViewportView(tabel_kembali);

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print-48.png"))); // NOI18N
        btnCetak.setText("Print");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        btnPDF.setText("Save to Pdf");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnXls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnXls.setText("Save to Excel");
        btnXls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXlsActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon (1).png"))); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnCetak)
                .addGap(14, 14, 14)
                .addComponent(btnPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXls)
                    .addComponent(btnDelete))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Pengembalian", jPanel1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA LAPORAN");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan.png"))); // NOI18N
        jMenu1.setText("Laporan");

        mnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-48.png"))); // NOI18N
        mnTutup.setText("Tutup");
        mnTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnTutupMousePressed(evt);
            }
        });
        jMenu1.add(mnTutup);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTutupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTutupMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnTutupMousePressed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("DATA LAPORAN PENGEMBALIAN");
        
        MessageFormat footer = new MessageFormat("KETUA PAKET KEAHLIAN TKJ DAN MM      :   Drs. Triantoro");
        
        try {
            
            tabel_kembali.print(JTable.PrintMode.NORMAL, header, footer);
     
        }
        catch (java.awt.print.PrinterException e) {
            
            System.err.format("Tidak Bisa Print %s%n", e.getMessage());
       
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
        try {
                
                konek.st = konek.conn.createStatement();
                String query = "SELECT nis, nama, kelas, jurusan, DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam,"
                        + "DATE_FORMAT(tgl_kembali, '%d/%m/%Y') AS tanggal_kembali, jam_kembali "
                        + "FROM tb_peminjaman WHERE tgl_kembali ORDER BY tgl_pinjam DESC";
                
                konek.rs = konek.st.executeQuery(query);
     
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Laporan Pengembalian Alat.pdf"));
                document.open();
                document.addTitle("DATA PENGEMBALIAN HARI INI");
                document.add(new Paragraph("DATA PENGEMBALIAN HARI INI"));
                document.add (new Paragraph(" "));
                PdfPTable table = new PdfPTable(7);
                PdfPCell c1 = new PdfPCell (new Phrase("NIS"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c1);
                
                PdfPCell c2 = new PdfPCell (new Phrase("Nama"));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c2);
                
                PdfPCell c3 = new PdfPCell (new Phrase("Kelas"));
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c3);
                
                PdfPCell c4 = new PdfPCell (new Phrase("Jurusan"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
                
                PdfPCell c5 = new PdfPCell (new Phrase("Tanggal Pinjam"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
             
                PdfPCell c6 = new PdfPCell (new Phrase("Tanggal Kembali"));
                c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c6);
                
                PdfPCell c7 = new PdfPCell (new Phrase("Jam Kembali"));
                c7.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c7);
                
                
                
                while (konek.rs.next()){
                    
                    try {
                        
                        table.addCell(konek.rs.getString("nis"));
                        table.addCell(konek.rs.getString("nama"));
                        table.addCell(konek.rs.getString("kelas"));
                        table.addCell(konek.rs.getString("jurusan"));
                        table.addCell(konek.rs.getString("tanggal_pinjam"));
                        table.addCell(konek.rs.getString("tanggal_kembali"));
                        table.addCell(konek.rs.getString("jam_kembali"));
                        
                    }
                    
                    catch (Exception e) {
                        
                    }
                }
                
                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Berhasil simpan di drive anda, Lokasi di sebelah/dalam folder project ");
                
            } catch(Exception e){
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnXlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXlsActionPerformed
        // TODO add your handling code here:
        
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = tabel_kembali.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           
            // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
            }
                fileWriter.write("\n");
            // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                for(int j=0; j < tModel.getColumnCount(); j++) {
                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
            }
                fileWriter.write("\n");
            }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnXlsActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = tabel_pinjam.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));
                // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                    fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
                }
                fileWriter.write("\n");
                // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                    for(int j=0; j < tModel.getColumnCount(); j++) {
                        fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
                    }
                    fileWriter.write("\n");
                }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
    // TODO add your handling code here:
    
            try {
                
                konek.st = konek.conn.createStatement();
                String query = "SELECT nama, kelas, jurusan, nama_barang, jumlah_barang, jam_pinjam,"
                    + "DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam FROM tb_peminjaman";
                konek.rs = konek.st.executeQuery(query);
                
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Laporan Peminjaman Alat.pdf"));
                document.open();
                document.addTitle("DATA PEMINJAMAN HARI INI");
                document.add(new Paragraph("DATA PEMINJAMAN HARI INI"));
                document.add (new Paragraph(" "));
                PdfPTable table = new PdfPTable(7);
                PdfPCell c1 = new PdfPCell (new Phrase("Nama"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c1);
                
                PdfPCell c2 = new PdfPCell (new Phrase("Kelas"));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c2);
                
                PdfPCell c3 = new PdfPCell (new Phrase("Jurusan"));
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c3);
                
                PdfPCell c4 = new PdfPCell (new Phrase("Nama Barang"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
             
                PdfPCell c5 = new PdfPCell (new Phrase("Jumlah Barang"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c5);
                
                PdfPCell c6 = new PdfPCell (new Phrase("Jam Pinjam"));
                c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c6);
                
                PdfPCell c7 = new PdfPCell (new Phrase("Tanggal Pinjam"));
                c7.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c7);
                
                
                while (konek.rs.next()){
                    
                    try {
                        
                        table.addCell(konek.rs.getString("nama"));
                        table.addCell(konek.rs.getString("kelas"));
                        table.addCell(konek.rs.getString("jurusan"));
                        table.addCell(konek.rs.getString("nama_barang"));
                        table.addCell(konek.rs.getString("jumlah_barang"));
                        table.addCell(konek.rs.getString("jam_pinjam"));
                        table.addCell(konek.rs.getString("tanggal_pinjam"));
                        
                    }
                    
                    catch (Exception e) {
                        
                    }
                }
                
                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Berhasil simpan di drive anda, Lokasi di sebelah/dalam folder project");
                
            } catch(Exception e){
        }
    }//GEN-LAST:event_btnPdfActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("DATA LAPORAN PEMINJAMAN");

        MessageFormat footer = new MessageFormat("KETUA PAKET KEAHLIAN TKJ DAN MM      :   Drs. Triantoro");

        try {

            tabel_pinjam.print(JTable.PrintMode.NORMAL, header, footer);

        }
        catch (java.awt.print.PrinterException e) {

            System.err.format("Tidak Bisa Print %s%n", e.getMessage());

        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        peminjaman = (DefaultTableModel) tabel_pinjam.getModel();
        try {
         
         int index = tabel_pinjam.getSelectedRow();
         peminjaman.removeRow(index);
         
        } catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null, ex);
        }
         
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        pengembalian = (DefaultTableModel) tabel_kembali.getModel();
        try {
         
         int index = tabel_kembali.getSelectedRow();
         pengembalian.removeRow(index);
         
        } catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
   
    
    public void tampil_pinjam(){
        
        peminjaman = (DefaultTableModel) tabel_pinjam.getModel(); 
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT nama, kelas, jurusan, nama_barang, jumlah_barang, jam_pinjam,"
                    + "DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam FROM tb_peminjaman";
            
            konek.rs = konek.st.executeQuery(query);
            int i = 0;
            while (konek.rs.next()) {
                i++;
                
                String nama = konek.rs.getString("nama");
                String kelas = konek.rs.getString("kelas");
                String jurusan = konek.rs.getString("jurusan");
                String nama_barang = konek.rs.getString("nama_barang");
                String jumlah_barang = konek.rs.getString("jumlah_barang");
                String jam_pinjam = konek.rs.getString("jam_pinjam");
                String tgl_pinjam = konek.rs.getString("tanggal_pinjam");
              
             
                String [] data = {nama, kelas, jurusan, nama_barang, jumlah_barang, jam_pinjam, tgl_pinjam};
                peminjaman.addRow(data);
            }
            if (i==0) {
                JOptionPane.showMessageDialog(this, "Hari ini belum ada peminjaman alat");
          }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tabel_pinjam.setModel(peminjaman);
    }

 public void tampil_kembali(){
        
        pengembalian = (DefaultTableModel) tabel_kembali.getModel(); 
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT nis, nama, kelas, jurusan,  DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam, "
                    + "DATE_FORMAT(tgl_kembali, '%d/%m/%Y') AS tanggal_kembali, jam_kembali "
                    + "FROM tb_peminjaman WHERE tgl_kembali ORDER BY tgl_pinjam DESC";
            konek.rs = konek.st.executeQuery(query);
            int i = 0;
            while (konek.rs.next()) {
                i++;
                
                String nis = konek.rs.getString("nis");
                String nama = konek.rs.getString("nama");
                String kelas = konek.rs.getString("kelas");
                String jurusan = konek.rs.getString("jurusan");
                String tgl_pinjam = konek.rs.getString("tanggal_pinjam");
                String tgl_kembali = konek.rs.getString("tanggal_kembali");
                String jam_kembali = konek.rs.getString("jam_kembali");
              
             
                String [] data = {nis, nama, kelas, jurusan, tgl_pinjam, tgl_kembali, jam_kembali};
                pengembalian.addRow(data);
            }
            if (i==0) {
                JOptionPane.showMessageDialog(this, "Hari ini belum ada pengembalian alat");
          }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tabel_kembali.setModel(pengembalian);
 }
 

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnXls;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnTutup;
    private javax.swing.JTable tabel_kembali;
    private javax.swing.JTable tabel_pinjam;
    // End of variables declaration//GEN-END:variables

    
}
