
package ta_peminjamanalat;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class fPeminjamanGuru extends javax.swing.JFrame {
    
    DefaultTableModel masuk, keluar;
    koneksi konek = new koneksi();
    public fPeminjamanGuru() {
        
        konek.koneksi();
        initComponents();
        
        btnSimpan.setBackground(Color.green);
        btnReset.setBackground(Color.red);
        btnCari.setBackground(Color.yellow);
        btnCek.setBackground(Color.red);
        btnCetak.setBackground(Color.green);
        btnClear.setBackground(Color.blue);
        btnUbah.setBackground(Color.yellow);
        btnHapus.setBackground(Color.blue);
        
        tampil_masuk();
        tampil_keluar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMasuk = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtNamabrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtJumlahbrg = new javax.swing.JTextField();
        cboMapel = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKeluar = new javax.swing.JTable();
        txtKNamaB = new javax.swing.JTextField();
        txtKNama = new javax.swing.JTextField();
        txtKMapel = new javax.swing.JTextField();
        txtKPinjam = new javax.swing.JTextField();
        txtKJumlahB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtKNip = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnPeminjaman = new javax.swing.JMenu();
        mnKeluar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA PEMINJAMAN ALAT ");

        jLabel2.setText("Nama ");

        jLabel3.setText("Mapel");

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-icon.png"))); // NOI18N
        btnSimpan.setText("Pinjam");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnReset.setText("Refresh");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tbMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama B", "Nama", "Jumlah B", "Mapel", "Tgl Pinjam"
            }
        ));
        tbMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMasuk);

        jLabel5.setText("Nama Barang");

        txtNamabrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamabrgActionPerformed(evt);
            }
        });

        jLabel8.setText("Jumlah Barang");

        txtJumlahbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahbrgActionPerformed(evt);
            }
        });

        cboMapel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Mapel--", "Matematika ", "Bahasa Indonesia ", "Bahasa Inggris", "Bahasa Jawa", "Fisika ", "Kimia", "Seni Budaya", "Sejarah ", "PAI ", "PPKN", "Prakarya dan KWR", "Penjasorkes", "Produktif" }));

        jLabel14.setText("NIP ");

        txtNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNipActionPerformed(evt);
            }
        });
        txtNip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNipKeyTyped(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel4.setText("Stok Barang");

        txtStok.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txtNip))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamabrg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(37, 37, 37)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnHapus)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cboMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStok)
                                    .addComponent(txtJumlahbrg, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                .addGap(56, 56, 56)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamabrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtJumlahbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Data Peminjaman", jPanel1);

        jLabel6.setText("Nama");

        jLabel7.setText("Mapel");

        jLabel9.setText("Tgl Pinjam");

        jLabel10.setText("Nama Barang");

        jLabel11.setText("Jumlah Barang");

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnCek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/koin.png"))); // NOI18N
        btnCek.setText("Cek Pinjam");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print-48.png"))); // NOI18N
        btnCetak.setText("Print Data");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clear Symbol-48.png"))); // NOI18N
        btnClear.setText("Bersihkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tbKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama B", "Nama", "Jmlh B", "Mapel", "Tgl  Pinjam", "Jam Pinjam"
            }
        ));
        tbKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKeluar);

        txtKNamaB.setEditable(false);

        txtKNama.setEditable(false);

        txtKMapel.setEditable(false);

        txtKPinjam.setEditable(false);

        txtKJumlahB.setEditable(false);

        jLabel15.setText("NIP");

        txtKNip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKNipKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKNama, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(txtKNip))
                                .addGap(32, 32, 32)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtKMapel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(txtKPinjam))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtKJumlahB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtKNamaB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtKNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtKNamaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(txtKJumlahB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jTabbedPane1.addTab("Laporan Peminjaman", jPanel2);

        mnPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Peminjaman.png"))); // NOI18N
        mnPeminjaman.setText("Menu Peminjaman");

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-48.png"))); // NOI18N
        mnKeluar.setText("Tutup");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnPeminjaman.add(mnKeluar);

        jMenuBar1.add(mnPeminjaman);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        if (txtNip.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIP belum diisi!");
        } else if (txtNamabrg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang belum diisi!");
        } else if (txtNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        } else if (txtJumlahbrg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah Barang belum diisi!");
        } else if (txtStok.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Barang yang akan di pinjam Tidak Tersedia");
        } else if (cboMapel.getSelectedItem().equals("-Pilih Mapel-")) {
            JOptionPane.showMessageDialog(this, "Mata Pelajaran belum dipilih");
        } else {
        
            Double stok_barang = Double.valueOf(txtStok.getText());
            Double jmlh_barang = Double.valueOf(txtJumlahbrg.getText());
       
        if (stok_barang < jmlh_barang) {
            
        JOptionPane.showMessageDialog(this, "Stok Barang Tidak tersedia");
        } else {
            
            String nip, nama_barang, nama, jumlah_barang, mapel, sql, query;
            nip = txtNip.getText();
            nama_barang = txtNamabrg.getText();
            nama = txtNama.getText();
            jumlah_barang = txtJumlahbrg.getText();
            mapel = cboMapel.getSelectedItem().toString();
 
            sql = "INSERT INTO tb_peminjamanguru(nip, nama_barang,nama,jumlah_barang,mapel,tgl_pinjam)"
                  + "VALUES('"+nip+"','"+nama_barang+"','"+nama+"','"+jumlah_barang+"','"+mapel+"', CURDATE())";
            query = "UPDATE tb_peralatan SET stok_barang = stok_barang-"+jumlah_barang+" WHERE nama_barang = '"+nama_barang+"'";
        
            try {
                konek.st = konek.conn.createStatement();
                konek.st.execute(sql);
                konek.st.executeUpdate(query);
                
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal disimpan"+e);
                return;
            }
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        }
        
        resetAll();
        tampil_masuk();
        tampil_keluar();
       
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtJumlahbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahbrgActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if(txtKNip.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "NIP Masih Kosong");
        
        else {
            
           String sql = "SELECT nama, mapel, DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam, nama_barang, jumlah_barang "
                   + "FROM tb_peminjamanguru WHERE nip='"+txtKNip.getText()+"'";
           try
                
            {
                konek.st = konek.conn.createStatement();
                konek.rs = konek.st.executeQuery(sql);
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(this, "Kesalahan query"+ex);
            }
             
             int size=0;
             try {
                while (konek.rs.next()){
                    size++;
           
                    txtKNama.setText(konek.rs.getString("nama").toString());
                    txtKMapel.setText(konek.rs.getString("mapel").toString());
                    txtKPinjam.setText(konek.rs.getString("tanggal_pinjam").toString());
                    txtKNamaB.setText(konek.rs.getString("nama_barang").toString());
                    txtKJumlahB.setText(konek.rs.getString("jumlah_barang").toString());
                
            }
                if(size==0)
                {
                    JOptionPane.showMessageDialog(this,"Data tidak ditemukan");
                    return;
                }
                konek.rs.close();
                konek.st.close();
            } catch (SQLException ex){
            
        }
    }//GEN-LAST:event_btnCariActionPerformed
 }
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtKNip.setText("");
        txtKNamaB.setText("");
        txtKNama.setText("");
        txtKMapel.setText("");
        txtKPinjam.setText("");
        txtKJumlahB.setText("");
       
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
         if(txtKNip.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Data kosong!");
        else {
             
            String sql, nip;
            nip = txtKNip.getText();
            
            sql = "UPDATE tb_peminjamanguru SET jam_pinjam=CURTIME() WHERE nip='"+nip+"'";
                try{
                    konek.st = konek.conn.createStatement();
                    konek.st.execute(sql);
                    
                }
                catch (SQLException e){
                    JOptionPane.showMessageDialog(this, "Data gagal disimpan"+e);
                    return;
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diperbaharui");
            
            resetAll();
            tampil_masuk();
            tampil_keluar();
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        
        if (txtKNip.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data masing kosong!");
        } else {
            PrintJob p = getToolkit().getPrintJob(this, "Cetak Tiket", null);

            Graphics g = p.getGraphics();
            g.setFont(new Font("Serif", Font.BOLD, 20));
            g.drawString("NIP : "+txtKNip.getText(), 200, 30);
            g.drawLine(20, 40, 700, 40);
            
            g.setFont(new Font("Courier New", Font.PLAIN, 12));
            g.drawString("Nama Barang", 10, 50);
            g.drawString("    : ", 100, 50);
            g.drawString(txtKNamaB.getText(), 160, 50);
               
            g.drawString("Nama", 10, 60);
            g.drawString("    : ", 100, 60);
            g.drawString(txtKNama.getText(), 160, 60);
            
            g.drawString("Mata Pelajaran", 10, 70);
            g.drawString("    : ", 100, 70);
            g.drawString(txtKMapel.getText(), 160, 70);
            
            g.drawString("Tanggal Pinjam", 10, 80);
            g.drawString("    : ", 100, 80);
            g.drawString(txtKPinjam.getText(), 160, 80);
            
            g.drawString("Jumlah Barang", 10, 90);
            g.drawString("    : ", 100, 90);
            g.drawString(txtKJumlahB.getText(), 160, 90);

 

            
            g.setFont(new Font("Courier New", Font.PLAIN, 8));
            g.drawString("*Apabila Barang yang dipinjam rusak menjadi tanggungjawab peminjam", 10, 150);
            g.drawString("*Apabila Barang hilang juga menjadi tanggungjawab peminjam dengan mengganti barang tersebut", 10, 160);
            g.drawString("*Terima Kasih sudah merawat barang dengan baik", 10, 170);

            p.end();
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void txtNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNipActionPerformed

    private void txtNipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNipKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtNipKeyTyped

    private void txtKNipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKNipKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtKNipKeyTyped

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
          int index = tbMasuk.getSelectedRow();
         String jumlah_barang, nama_barang, sql, query;
          
         nama_barang = txtNamabrg.getText();
         jumlah_barang = txtJumlahbrg.getText();
         
         sql = "DELETE FROM tb_peminjamanguru WHERE nip = '"+txtNip.getText()+"'";
         query = "UPDATE tb_peralatan SET stok_barang = "+jumlah_barang+" + stok_barang WHERE nama_barang = '"+nama_barang+"'";
   
         masuk.removeRow(index);
          
          try {
              
              konek.st = konek.conn.createStatement();
              konek.st.execute(sql);
              konek.st.executeUpdate(query);
          }
          catch (SQLException e){
              JOptionPane.showMessageDialog(this, "Data gagal dihapus"+e);
              return;
          }
          JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
          
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tbKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKeluarMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_tbKeluarMouseClicked

    private void tbMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMasukMouseClicked
        // TODO add your handling code here:
        
        try {
        
        int row = tbMasuk.rowAtPoint(evt.getPoint());

        String nis = tbMasuk.getValueAt(row, 0).toString();
        String nama_barang = tbMasuk.getValueAt(row, 1).toString();
        String nama = tbMasuk.getValueAt(row, 2).toString();
        String jumlah_barang = tbMasuk.getValueAt(row, 3).toString();
        String mapel = tbMasuk.getValueAt(row, 4).toString();
 
            txtNip.setText(String.valueOf(nis));
            txtNamabrg.setText(String.valueOf(nama_barang));
            txtNama.setText(String.valueOf(nama));
            txtJumlahbrg.setText(String.valueOf(jumlah_barang));
            cboMapel.setSelectedItem(String.valueOf(mapel));
      
            } 
        
        catch (Exception e) {

        }
    }//GEN-LAST:event_tbMasukMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtNip.setText("");
        txtNamabrg.setText("");
        txtStok.setText("");
        txtNama.setText("");
        txtJumlahbrg.setText("");
        cboMapel.setSelectedIndex(0);
 
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        
        if (txtNamabrg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang belum diisi!");
        } else if (txtNip.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIP belum diisi!");
        } else if (txtNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        } else if (txtJumlahbrg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah Barang belum diisi!");
        } else if (cboMapel.getSelectedItem().equals("-Pilih Kelas-")) {
            JOptionPane.showMessageDialog(this, "Kelas belum dipilih");
        } else {
            
            String sql = "update tb_peminjamanguru set"
                    +" nip = '"+txtNip.getText()+"',"
                    +" nama_barang = '"+txtNamabrg.getText()+"',"
                    +" nama = '"+txtNama.getText()+"',"
                    +" mapel = '"+cboMapel.getSelectedItem()+"' where"
                    +" jumlah_barang = '"+txtJumlahbrg.getText()+"'";
            
            try {
                
                konek.st = konek.conn.createStatement();
                konek.st.executeUpdate(sql);
            }
            
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal diubah"+e);
                return; 
                }
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
        }
        
        resetAll();
        tampil_masuk();
        tampil_keluar();     
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtNamabrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamabrgActionPerformed
        // TODO add your handling code here:
        
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT * FROM tb_peralatan WHERE nama_barang = '"+txtNamabrg.getText()+"'";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                txtStok.setText(konek.rs.getString("stok_barang"));
                
            } 
        
        } catch (SQLException e){
            
            JOptionPane.showMessageDialog(this, "Data berhasil ditemukan"+e);
        }
    }//GEN-LAST:event_txtNamabrgActionPerformed
     
    public void resetAll(){
        
        txtNip.setText("");
        txtNamabrg.setText("");
        txtNama.setText("");
        txtStok.setText("");
        txtJumlahbrg.setText("");
        cboMapel.setSelectedIndex(0);
        
        masuk = (DefaultTableModel) tbMasuk.getModel();
        keluar = (DefaultTableModel) tbKeluar.getModel();
       
        int rowCount1 = masuk.getRowCount();
        int rowCount2 = keluar.getRowCount();
        //Remove rows one by one from the end of the table
        
        for (int i = rowCount1 - 1; i >= 0; i--) {
            masuk.removeRow(i);
        }
        for (int i = rowCount2 - 1; i >= 0; i--) {
            keluar.removeRow(i);
        }
    }
    
    public void tampil_masuk(){
        
        masuk = (DefaultTableModel) tbMasuk.getModel();
        
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT nip, nama_barang, nama, jumlah_barang, mapel, "
                    + "DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam FROM tb_peminjamanguru";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                String nip = konek.rs.getString("nip");
                String nama_barang = konek.rs.getString("nama_barang");
                String nama = konek.rs.getString("nama");
                String jumlah_barang = konek.rs.getString("jumlah_barang");
                String mapel = konek.rs.getString("mapel");
                String tgl_pinjam = konek.rs.getString("tanggal_pinjam");
                
                
                String [] data = {nip, nama_barang, nama, jumlah_barang, mapel, tgl_pinjam};
                masuk.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tbMasuk.setModel(masuk);
    }

       
    public void tampil_keluar(){
        
     keluar = (DefaultTableModel) tbKeluar.getModel();
     
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT nip, nama_barang, nama, jumlah_barang, mapel, DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam, jam_pinjam "
                    + "FROM tb_peminjamanguru WHERE jam_pinjam ORDER BY tgl_pinjam DESC";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                String nip = konek.rs.getString("nip");
                String nama_barang = konek.rs.getString("nama_barang");
                String nama = konek.rs.getString("nama");
                String jumlah_barang = konek.rs.getString("jumlah_barang");
                String mapel = konek.rs.getString("mapel");
                String tgl_pinjam = konek.rs.getString("tanggal_pinjam");
                String jam_pinjam = konek.rs.getString("jam_pinjam");

           
                String [] data = {nama_barang, nama, jumlah_barang, mapel, tgl_pinjam, jam_pinjam};
                keluar.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tbKeluar.setModel(keluar);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPeminjamanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPeminjamanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPeminjamanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPeminjamanGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPeminjamanGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cboMapel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenu mnPeminjaman;
    private javax.swing.JTable tbKeluar;
    private javax.swing.JTable tbMasuk;
    private javax.swing.JTextField txtJumlahbrg;
    private javax.swing.JTextField txtKJumlahB;
    private javax.swing.JTextField txtKMapel;
    private javax.swing.JTextField txtKNama;
    private javax.swing.JTextField txtKNamaB;
    private javax.swing.JTextField txtKNip;
    private javax.swing.JTextField txtKPinjam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamabrg;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables

    
}