/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_peminjamanalat;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author windows10
 */
public class fPengembalian extends javax.swing.JFrame {

    DefaultTableModel masuk, keluar;
    koneksi konek = new koneksi();
    /**
     * Creates new form fPengembalian
     */
    public fPengembalian() {
       
        konek.koneksi();
        initComponents();
      
        btnKembali.setBackground(Color.red);
        btnCek.setBackground(Color.blue);
        btnCari.setBackground(Color.green);
        btnSearch.setBackground(Color.yellow);
        btnClear.setBackground(Color.blue);
        btnHapus.setBackground(Color.red);
        btnCetak.setBackground(Color.green);
        btnDelete.setBackground(Color.yellow);
       
        tampil_masuk();
        tampil_keluar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNis = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtJurusan = new javax.swing.JTextField();
        txtNamaB = new javax.swing.JTextField();
        txtJumlahB = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMasuk = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPinjam = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtKNis = new javax.swing.JTextField();
        txtKNama = new javax.swing.JTextField();
        txtKKelas = new javax.swing.JTextField();
        txtKJurusan = new javax.swing.JTextField();
        txtKNamaB = new javax.swing.JTextField();
        txtKJumlahB = new javax.swing.JTextField();
        txtKPinjam = new javax.swing.JTextField();
        txtKKembali = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKeluar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnTutup = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("NIS ");

        jLabel3.setText("Nama");

        jLabel4.setText("Kelas");

        jLabel5.setText("Jurusan");

        jLabel7.setText("Nama Barang");

        jLabel8.setText("Jumlah Barang");

        txtNis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNisKeyTyped(evt);
            }
        });

        txtNama.setEditable(false);

        txtKelas.setEditable(false);

        txtJurusan.setEditable(false);

        txtNamaB.setEditable(false);

        txtJumlahB.setEditable(false);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnClear.setText("Refresh");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tbMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kelas", "Jurusan ", "Nama B", "Jmlh B", "Tgl Pinjam", "Tgl Kembali"
            }
        ));
        tbMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMasuk);

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pengembalian.png"))); // NOI18N
        btnKembali.setText("Alat Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel9.setText("Tanggal Pinjam ");

        txtPinjam.setEditable(false);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon.png"))); // NOI18N
        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaB, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txtJumlahB)
                                    .addComponent(txtPinjam))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(btnKembali)
                                .addGap(26, 26, 26)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCari)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Pengembalian ", jPanel1);

        jLabel6.setText("NIS");

        jLabel10.setText("Nama ");

        jLabel11.setText("Kelas ");

        jLabel12.setText("Jurusan ");

        jLabel13.setText("Nama Barang");

        jLabel14.setText("Jumlah Barang");

        jLabel15.setText("Tanggal Pinjam");

        jLabel16.setText("Tanggal Kembali");

        txtKNis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKNisKeyTyped(evt);
            }
        });

        txtKNama.setEditable(false);

        txtKKelas.setEditable(false);
        txtKKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKKelasActionPerformed(evt);
            }
        });

        txtKJurusan.setEditable(false);

        txtKNamaB.setEditable(false);

        txtKJumlahB.setEditable(false);

        txtKPinjam.setEditable(false);

        txtKKembali.setEditable(false);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print-48.png"))); // NOI18N
        btnCetak.setText("Cetak Data");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnHapus.setText("Refresh");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        btnCek.setText("Cek Kembali");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        tbKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kelas ", "Jurusan", "Tgl Pinjam ", "Tgl Kembali", "Jam Pinjam", "Jam Kembali"
            }
        ));
        tbKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKeluar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCetak)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnCek))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKNis, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtKNama)
                                    .addComponent(txtKKelas)
                                    .addComponent(txtKJurusan))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKNamaB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(txtKJumlahB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKPinjam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKKembali, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(txtKNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKNamaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKJumlahB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel14)
                        .addComponent(txtKNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(txtKKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtKJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtKKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCek)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Laporan Pengembalian", jPanel2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("DATA PENGEMBALIAN ALAT");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pengembalian2.png"))); // NOI18N
        jMenu1.setText("Data Pengembalian");

        mnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-48.png"))); // NOI18N
        mnTutup.setText("Tutup");
        mnTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnTutupMousePressed(evt);
            }
        });
        mnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTutupActionPerformed(evt);
            }
        });
        jMenu1.add(mnTutup);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTutupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTutupMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnTutupMousePressed

    private void txtKKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKKelasActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
        if(txtNis.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "NIS Masih Kosong");
        else {
            
           String sql = "SELECT nama, kelas, jurusan, nama_barang, jumlah_barang, "
                   + "DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam "
                   + "FROM tb_peminjaman WHERE nis='"+txtKNis.getText()+"'";
            try
            {
                konek.st = konek.conn.createStatement();
                konek.rs = konek.st.executeQuery(sql);
                
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(this, "Kesalahan query"+ex);
            }
             int size=0;
             try {
                while (konek.rs.next()){
                    size++;
                     
                    txtNama.setText(konek.rs.getString("nama").toString());
                    txtKelas.setText(konek.rs.getString("kelas").toString());
                    txtJurusan.setText(konek.rs.getString("jurusan").toString());
                    txtNamaB.setText(konek.rs.getString("nama_barang").toString());
                    txtJumlahB.setText(konek.rs.getString("jumlah_barang").toString());
                    txtPinjam.setText(konek.rs.getString("tanggal_pinjam").toString());    
        }
                if(size==0)
                {
                    JOptionPane.showMessageDialog(this,"Data tidak ditemukan");
                    return;
                }
                konek.rs.close();
                konek.st.close();
            } catch (SQLException ex){
            }
    }      
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txtKNis.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "NIS Masih Kosong");
        else {
            
            String sql = "SELECT nama, kelas, jurusan, nama_barang, jumlah_barang, "
                   + "DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam, "
                    + "DATE_FORMAT(tgl_kembali, '%d/%m/%Y') AS tanggal_kembali "
                   + "FROM tb_peminjaman WHERE nis='"+txtKNis.getText()+"'";
            try
            {
                konek.st = konek.conn.createStatement();
                konek.rs = konek.st.executeQuery(sql);
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(this, "Kesalahan query"+ex);
            }
             int size=0;
             try {
                while (konek.rs.next()){
                    size++;
            
                    txtKNama.setText(konek.rs.getString("nama").toString());
                    txtKKelas.setText(konek.rs.getString("kelas").toString());
                    txtKJurusan.setText(konek.rs.getString("jurusan").toString());
                    txtKNamaB.setText(konek.rs.getString("nama_barang").toString());
                    txtKJumlahB.setText(konek.rs.getString("jumlah_barang").toString());
                    txtKPinjam.setText(konek.rs.getString("tanggal_pinjam").toString());
                    txtKKembali.setText(konek.rs.getString("tanggal_kembali").toString());   
        }
                if(size==0)
                {
                    JOptionPane.showMessageDialog(this,"Data tidak ditemukan");
                    return;
                }
                konek.rs.close();
                konek.st.close();
            } catch (SQLException ex){
            }
    }      
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtNis.setText("");
        txtNamaB.setText("");
        txtNama.setText("");
        txtKelas.setText("");
        txtJurusan.setText("");
        txtJumlahB.setText("");
        txtPinjam.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtKNis.setText("");
        txtKNamaB.setText("");
        txtKNama.setText("");
        txtKKelas.setText("");
        txtKJurusan.setText("");
        txtKJumlahB.setText("");
        txtKPinjam.setText("");
        txtKKembali.setText("");
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        if(txtNis.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Data kosong!");
        else {
             
            String sql, nis, query;
            nis = txtNis.getText();
            
            sql = "UPDATE tb_peminjaman SET tgl_kembali=CURDATE() WHERE nis='"+nis+"'";
            query = "UPDATE tb_peralatan SET stok_barang = stok_barang+"+txtJumlahB.getText()+" WHERE nama_barang = '"+txtNamaB.getText()+"'"; 
            
            try {
                    konek.st = konek.conn.createStatement();
                    konek.st.execute(sql);
                    konek.st.executeUpdate(query);
                    
                }
                catch (SQLException e){
                    JOptionPane.showMessageDialog(this, "Data gagal disimpan"+e);
                    return;
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diperbaharui");
            
           
            tampil_masuk();
            tampil_keluar();
        }
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        if(txtKNis.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Data kosong!");
        else {
             
            String sql, nis;
            nis = txtKNis.getText();
            
            sql = "UPDATE tb_peminjaman SET jam_kembali=CURTIME() WHERE nis='"+nis+"'";
                
            try {
                    konek.st = konek.conn.createStatement();
                    konek.st.execute(sql);
                    
                }
                catch (SQLException e){
                    JOptionPane.showMessageDialog(this, "Data gagal disimpan"+e);
                    return;
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diperbaharui");
            
           
            tampil_masuk();
            tampil_keluar();
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
         if (txtKNis.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data masing kosong!");
        } else {
            PrintJob p = getToolkit().getPrintJob(this, "Cetak Tiket", null);

            Graphics g = p.getGraphics();
            g.setFont(new Font("Serif", Font.BOLD, 20));
            g.drawString("NIS : "+txtKNis.getText(), 200, 30);
            g.drawLine(20, 40, 700, 40);
            
            g.setFont(new Font("Courier New", Font.PLAIN, 12));
            g.drawString("Nama Barang", 10, 50);
            g.drawString("    : ", 100, 50);
            g.drawString(txtKNamaB.getText(), 160, 50);
               
            g.drawString("Nama", 10, 60);
            g.drawString("    : ", 100, 60);
            g.drawString(txtKNama.getText(), 160, 60);
            
            g.drawString("Kelas", 10, 70);
            g.drawString("    : ", 100, 70);
            g.drawString(txtKKelas.getText(), 160, 70);
            
            g.drawString("Jurusan", 10, 80);
            g.drawString("    : ", 100, 80);
            g.drawString(txtKJurusan.getText(), 160, 80);
            
            g.drawString("Jumlah Barang", 10, 90);
            g.drawString("    : ", 100, 90);
            g.drawString(txtKJumlahB.getText(), 160, 90);

            g.drawString("Tanggal Pinjam", 10, 100);
            g.drawString("    : ", 100, 100);
            g.drawString(txtKPinjam.getText(), 160, 100);
            
            g.drawString("Tanggal Kembali", 10, 110);
            g.drawString("    : ", 100, 110);
            g.drawString(txtKKembali.getText(), 160, 110);

            
            
            g.setFont(new Font("Courier New", Font.PLAIN, 8));
            g.drawString("*Apabila Barang yang dipinjam rusak menjadi tanggungjawab peminjam", 10, 150);
            g.drawString("*Apabila Barang hilang juga menjadi tanggungjawab peminjam dengan mengganti barang tersebut", 10, 160);
            g.drawString("*Terim Kasih sudah merawat barang dengan baik", 10, 170);

            p.end();
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void txtNisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNisKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtNisKeyTyped

    private void txtKNisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKNisKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtKNisKeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
            
          int index = tbMasuk.getSelectedRow();
          String sql;
          sql = "DELETE FROM tb_peminjaman WHERE nama = '"+txtNama.getText()+"'";
          masuk.removeRow(index);
          
          try {
              
              konek.st = konek.conn.createStatement();
              konek.st.execute(sql);
          }
          
          catch (SQLException e){
              JOptionPane.showMessageDialog(this, "Data gagal dihapus"+e);
              return;
          
          }

          JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void mnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnTutupActionPerformed

    private void tbMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMasukMouseClicked
        // TODO add your handling code here:
        
        try   {
        
        int row = tbMasuk.rowAtPoint(evt.getPoint());
        
        String nama = tbMasuk.getValueAt(row, 0).toString();
        String kelas = tbMasuk.getValueAt(row, 1).toString();
        String jurusan = tbMasuk.getValueAt(row, 2).toString();
        String nama_barang = tbMasuk.getValueAt(row, 3).toString();
        String jumlah_barang = tbMasuk.getValueAt(row, 4).toString();
        String tgl_pinjam = tbMasuk.getValueAt(row, 5).toString();
       

        txtNama.setText(String.valueOf(nama));
        txtKelas.setText(String.valueOf(kelas));
        txtJurusan.setText(String.valueOf(jurusan));
        txtNamaB.setText(String.valueOf(nama_barang));
        txtJumlahB.setText(String.valueOf(jumlah_barang));
        txtPinjam.setText(String.valueOf(tgl_pinjam));
            
            
            } 
        
        catch (Exception e) {

        }
     
    }//GEN-LAST:event_tbMasukMouseClicked

    private void tbKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKeluarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbKeluarMouseClicked
 
    
    public void tampil_masuk(){
         masuk = (DefaultTableModel) tbMasuk.getModel();
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT nama, kelas, jurusan, nama_barang, jumlah_barang, "
                    + "DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam, "
                    + "DATE_FORMAT(tgl_kembali, '%d/%m/%Y') AS tanggal_kembali "
                    + "FROM tb_peminjaman WHERE tgl_kembali ORDER BY tgl_pinjam DESC";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                String nama = konek.rs.getString("nama");
                String kelas = konek.rs.getString("kelas");
                String jurusan = konek.rs.getString("jurusan");
                String nama_barang = konek.rs.getString("nama_barang");
                String jumlah_barang = konek.rs.getString("jumlah_barang");
                String tgl_pinjam = konek.rs.getString("tanggal_pinjam");
                String tgl_kembali = konek.rs.getString("tanggal_kembali");
                
                
                String [] data = {nama, kelas, jurusan, nama_barang, jumlah_barang, tgl_pinjam, tgl_kembali};
                masuk.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tbMasuk.setModel(masuk);
    }

       
    public void tampil_keluar(){
        
     keluar = (DefaultTableModel) tbKeluar.getModel();
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT nama, kelas, jurusan, DATE_FORMAT(tgl_pinjam, '%d/%m/%Y') AS tanggal_pinjam, "
                    + "DATE_FORMAT(tgl_kembali, '%d/%m/%Y') AS tanggal_kembali, jam_pinjam, jam_kembali "
                    + "FROM tb_peminjaman WHERE jam_kembali ORDER BY jam_pinjam DESC";
            konek.rs = konek.st.executeQuery(query);
            
            while (konek.rs.next()) {
                
                String nama = konek.rs.getString("nama");
                String kelas = konek.rs.getString("kelas");
                String jurusan = konek.rs.getString("jurusan");
                String tgl_pinjam = konek.rs.getString("tanggal_pinjam");
                String tgl_kembali = konek.rs.getString("tanggal_kembali");
                String jam_pinjam = konek.rs.getString("jam_pinjam");
                String jam_kembali = konek.rs.getString("jam_kembali");

                
                
                String [] data = {nama, kelas, jurusan, tgl_pinjam, tgl_kembali, jam_pinjam, jam_kembali};
                keluar.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tbKeluar.setModel(keluar);
   }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnTutup;
    private javax.swing.JTable tbKeluar;
    private javax.swing.JTable tbMasuk;
    private javax.swing.JTextField txtJumlahB;
    private javax.swing.JTextField txtJurusan;
    private javax.swing.JTextField txtKJumlahB;
    private javax.swing.JTextField txtKJurusan;
    private javax.swing.JTextField txtKKelas;
    private javax.swing.JTextField txtKKembali;
    private javax.swing.JTextField txtKNama;
    private javax.swing.JTextField txtKNamaB;
    private javax.swing.JTextField txtKNis;
    private javax.swing.JTextField txtKPinjam;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaB;
    private javax.swing.JTextField txtNis;
    private javax.swing.JTextField txtPinjam;
    // End of variables declaration//GEN-END:variables
}
