/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_peminjamanalat;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author windows10
 */

public class fPeralatan extends javax.swing.JFrame {

    
    DefaultTableModel masuk, keluar, keluar1;
    koneksi konek = new koneksi();
    /**
     * Creates new form fPeralatan
     */
    public fPeralatan() {
        
        konek.koneksi();
        initComponents();
        
        btnSimpan.setBackground(Color.green);
        btnReset.setBackground(Color.red);
        btnDelete.setBackground(Color.blue);
        btnCari.setBackground(Color.yellow);
        btnClear.setBackground(Color.blue);
        btnCari1.setBackground(Color.yellow);
        btnClear1.setBackground(Color.blue);
        btnPdf.setBackground(Color.green);
        btnPdf1.setBackground(Color.green);
        btnExcel.setBackground(Color.red);
        btnExcel1.setBackground(Color.red);
        
        tampil_masuk();
        tampil_keluar();
        tampil_keluar1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnReset1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNamaBrng = new javax.swing.JTextField();
        txtInventaris = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInput = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDana = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMAC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSpek = new javax.swing.JTextArea();
        cboKategori = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbStok = new javax.swing.JTable();
        btnPdf = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCari1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtCari2 = new javax.swing.JTextField();
        btnClear1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbTahun = new javax.swing.JTable();
        btnPdf1 = new javax.swing.JButton();
        btnExcel1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnTutup = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton2.setText("jButton2");

        jLabel8.setText("jLabel8");

        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA PERALATAN");

        jLabel2.setText("ID");

        jLabel3.setText("Nama Benda");

        jLabel4.setText("No. Inventaris");

        tbInput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Brg", "Nama B", "Spek", "No. Inv", "M/I", "Stk Brg", "Dana", "Tahun", "Kategori"
            }
        ));
        tbInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInputMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInput);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Refresh");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel9.setText("Spesifikasi");

        jLabel6.setText("MAC / IMEI");

        jLabel5.setText("Stok");

        jLabel10.setText("Sumber Dana");

        jLabel12.setText("Tahun Pengadaan");

        jLabel13.setText("Kategori");

        txtSpek.setColumns(20);
        txtSpek.setRows(5);
        jScrollPane3.setViewportView(txtSpek);

        cboKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Kategori--", "Alat", "Bahan", "Barang" }));

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaBrng, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStok)
                            .addComponent(txtMAC)
                            .addComponent(txtDana)
                            .addComponent(txtTahun)
                            .addComponent(cboKategori, 0, 192, Short.MAX_VALUE))))
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaBrng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInventaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Input Barang", jPanel1);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Barang / ID Barang");

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnClear.setText("Hapus");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tbStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Brg", "Nama B", "Spek", "No. Inv", "M/I", "Dana", "Tahun", "Kategori", "Stk Brg"
            }
        ));
        tbStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStokMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbStok);

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        btnPdf.setText("Save to Pdf");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExcel.setText("Save to Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcel)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPdf)
                    .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stok Barang", jPanel2);

        btnCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search Symbol.png"))); // NOI18N
        btnCari1.setText("Cari");
        btnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Tahun Pengadaan / Perolehan");

        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnClear1.setText("Hapus");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        tbTahun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tahun", "ID Brg", "Nama B", "Spek", "No. Inv", "M/I", "Stk Brg", "Dana", "Kategori"
            }
        ));
        tbTahun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTahunMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbTahun);

        btnPdf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        btnPdf1.setText("Save to Pdf");
        btnPdf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdf1ActionPerformed(evt);
            }
        });

        btnExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        btnExcel1.setText("Save to Excel");
        btnExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPdf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcel1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari1)
                    .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPdf1)
                    .addComponent(btnExcel1))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Tahun Pengadaan/Perolehan", jPanel3);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/peralatan.png"))); // NOI18N
        jMenu3.setText("Menu Peralatan");

        mnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-48.png"))); // NOI18N
        mnTutup.setText("Tutup");
        mnTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnTutupMousePressed(evt);
            }
        });
        mnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTutupActionPerformed(evt);
            }
        });
        jMenu3.add(mnTutup);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnTutupActionPerformed

    private void mnTutupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTutupMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnTutupMousePressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID belum diisi!");
        } else if (txtNamaBrng.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Benda belum diisi!");
        } else if (txtSpek.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Spesifikasi belum diisi!");
        } else if (txtInventaris.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No. Inventaris belum diisi!");
        } else if (txtMAC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "MAC / IMEI belum diisi!");
        } else if (txtStok.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stok belum diisi!");
        } else if (txtDana.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sumber Dana belum diisi!");
        } else if (txtTahun.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tahun Pengadaan / Perolehan belum diisi!");
        } else if (cboKategori.getSelectedItem().equals("-Pilih Kategori-")) {
            JOptionPane.showMessageDialog(this, "Kategori belum dipilih");
            
        } else {
            String id_barang, nama_barang, spek, inventaris, mac, stok, dana, tahun, kategori, sql;
            
            id_barang = txtID.getText();
            nama_barang = txtNamaBrng.getText();
            spek = txtSpek.getText();
            inventaris = txtInventaris.getText();
            mac = txtMAC.getText();
            stok = txtStok.getText();
            dana = txtDana.getText();
            tahun = txtTahun.getText();
            kategori = cboKategori.getSelectedItem().toString();
 
 sql = "INSERT INTO tb_peralatan(id_barang, nama_barang, spek, no_inventaris, mac, stok_barang, dana, tahun, kategori)"
 + "VALUES('"+id_barang+"','"+nama_barang+"','"+spek+"',"
         + "'"+inventaris+"','"+mac+"','"+stok+"','"+dana+"','"+tahun+"','"+kategori+"')";
            try {
                konek.st = konek.conn.createStatement();
                konek.st.execute(sql);  
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(this, "Data gagal disimpan"+e);
                return;
            }
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        }
        resetAll();
        tampil_masuk();
        tampil_keluar();
        tampil_keluar1();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtNamaBrng.setText("");
        txtSpek.setText("");
        txtInventaris.setText("");
        txtMAC.setText("");
        txtStok.setText("");
        txtDana.setText("");
        txtTahun.setText("");
        cboKategori.setSelectedIndex(0);
   
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        keluar = (DefaultTableModel) tbStok.getModel();
        try {
         
         int index = tbStok.getSelectedRow();
         keluar.removeRow(index);
         
        } catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
        keluar = (DefaultTableModel) tbStok.getModel();
        try {
            
            konek.st = konek.conn.createStatement();
            String sql = "SELECT * FROM tb_peralatan WHERE id_barang = '"+txtCari.getText()+"'"+
            "or nama_barang = '"+txtCari.getText()+"'";
            konek.rs = konek.st.executeQuery(sql);
            while (konek.rs.next()) {
                
                String id_barang = konek.rs.getString("id_barang");
                String nama_barang = konek.rs.getString("nama_barang");
                String spek = konek.rs.getString("spek");
                String inventaris = konek.rs.getString("no_inventaris");
                String mac = konek.rs.getString("mac");
                String dana = konek.rs.getString("dana");
                String tahun = konek.rs.getString("tahun");
                String kategori = konek.rs.getString("kategori");
                String stok = konek.rs.getString("stok_barang");
                
                
                String [] data = {id_barang, nama_barang, spek, inventaris, mac, dana, tahun, kategori, stok};
                keluar.addRow(data);
            }
    } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
    }
            tbStok.setModel(keluar);
    }//GEN-LAST:event_btnCariActionPerformed

    private void tbInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInputMouseClicked
        // TODO add your handling code here:
        
        try {
        
        int row = tbInput.rowAtPoint(evt.getPoint());

        String id_barang = tbInput.getValueAt(row, 0).toString();
        String nama_barang = tbInput.getValueAt(row, 1).toString();
        String spek = tbInput.getValueAt(row, 2).toString();
        String inventaris = tbInput.getValueAt(row, 3).toString();
        String mac = tbInput.getValueAt(row, 4).toString();
        String stok = tbInput.getValueAt(row, 5).toString();
        String dana = tbInput.getValueAt(row, 6).toString();
        String tahun = tbInput.getValueAt(row, 7).toString();
        String kategori = tbInput.getValueAt(row, 8).toString();
        
        

            txtID.setText(String.valueOf(id_barang));
            txtNamaBrng.setText(String.valueOf(nama_barang));
            txtSpek.setText(String.valueOf(spek));
            txtInventaris.setText(String.valueOf(inventaris));
            txtMAC.setText(String.valueOf(mac));
            txtStok.setText(String.valueOf(stok));
            txtDana.setText(String.valueOf(dana));
            txtTahun.setText(String.valueOf(tahun));
            cboKategori.setSelectedItem(String.valueOf(kategori));
        
            } catch (Exception e) {

        }
        
    }//GEN-LAST:event_tbInputMouseClicked

    private void tbStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbStokMouseClicked

    private void btnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari1ActionPerformed
        // TODO add your handling code here:
        
        keluar1 = (DefaultTableModel) tbTahun.getModel();
        try {
            konek.st = konek.conn.createStatement();
            String sql = "SELECT * FROM tb_peralatan WHERE no_inventaris = '"+txtCari2.getText()+"'"+
            "or tahun = '"+txtCari2.getText()+"'";
            konek.rs = konek.st.executeQuery(sql);
            while (konek.rs.next()) {
              
                String tahun = konek.rs.getString("tahun");
                String id_barang = konek.rs.getString("id_barang");
                String nama_barang = konek.rs.getString("nama_barang");
                String spek = konek.rs.getString("spek");
                String inventaris = konek.rs.getString("no_inventaris");
                String mac = konek.rs.getString("mac");
                String stok = konek.rs.getString("stok_barang");
                String dana = konek.rs.getString("dana");
                String kategori = konek.rs.getString("kategori");
                
                
                String [] data = {tahun, id_barang, nama_barang, spek, inventaris, mac, stok, dana,kategori};
                keluar1.addRow(data);
            }
    } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
    }
            tbTahun.setModel(keluar1);
    }//GEN-LAST:event_btnCari1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        
        keluar1 = (DefaultTableModel) tbTahun.getModel();
        try {
         
         int index = tbTahun.getSelectedRow();
         keluar1.removeRow(index);
         
        } catch (Exception ex) {
            
             JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void tbTahunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTahunMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTahunMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          
          int index = tbInput.getSelectedRow();
          String sql;
          sql = "DELETE FROM tb_peralatan WHERE id_barang = '"+txtID.getText()+"'";
          masuk.removeRow(index);
          
          try {
              
              konek.st = konek.conn.createStatement();
              konek.st.execute(sql);
          }
          catch (SQLException e){
              JOptionPane.showMessageDialog(this, "Data gagal dihapus"+e);
              return;
          }
          JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        // TODO add your handling code here:

        try     {
                konek.st = konek.conn.createStatement();
                String query = "SELECT * FROM tb_peralatan WHERE id_barang like '%"+txtCari.getText()+"%'"+
                "or nama_barang like '%"+txtCari.getText()+"%'";
                konek.rs = konek.st.executeQuery(query);
     
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Data Informasi Stok Barang.pdf"));
                document.open();
                document.addTitle("DAFTAR INFORMASI STOK BARANG");
                document.add(new Paragraph("DAFTAR INFORMASI STOK BARANG"));
                document.add (new Paragraph(" "));
                PdfPTable table = new PdfPTable(6);
                PdfPCell c1 = new PdfPCell (new Phrase("ID Barang"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c1);
                
                PdfPCell c2 = new PdfPCell (new Phrase("Nama Barang"));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c2);
                
                PdfPCell c3 = new PdfPCell (new Phrase("Spesifikasi"));
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c3);
                
                PdfPCell c4 = new PdfPCell (new Phrase("Dana"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
                
                PdfPCell c5 = new PdfPCell (new Phrase("Kategori"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c5);
                
                PdfPCell c6 = new PdfPCell (new Phrase("Stok Barang"));
                c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c6);
             
                while (konek.rs.next()){
                    try {
                        table.addCell(konek.rs.getString("id_barang"));
                        table.addCell(konek.rs.getString("nama_barang"));
                        table.addCell(konek.rs.getString("spek"));
                        table.addCell(konek.rs.getString("dana"));
                        table.addCell(konek.rs.getString("kategori"));
                        table.addCell(konek.rs.getString("stok_barang"));
                    }
                    catch (Exception e) {
                    }
                }
                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan, Data tersimpan didalam project");
            } catch(Exception e){
        }
    }//GEN-LAST:event_btnPdfActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                TableModel tModel = tbStok.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));
                
                // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                    fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
                }
                fileWriter.write("\n");
                // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                    for(int j=0; j < tModel.getColumnCount(); j++) {
                        fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
                    }
                    fileWriter.write("\n");
                }
                fileWriter.close();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPdf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdf1ActionPerformed
        
          // TODO add your handling code here:
        
          try     {
                
                konek.st = konek.conn.createStatement();
                String query = "SELECT * FROM tb_peralatan WHERE no_inventaris like '%"+txtCari2.getText()+"%'"+
                "or tahun like '%"+txtCari2.getText()+"%'";
                konek.rs = konek.st.executeQuery(query);
     
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream("Data Informasi Pengadaan Barang.pdf"));
                document.open();
                document.addTitle("DAFTAR INFORMASI PENGADAAN BARANG");
                document.add(new Paragraph("DAFTAR INFORMASI PENGADAAN BARANG"));
                document.add (new Paragraph(" "));
                PdfPTable table = new PdfPTable(7);
                
                PdfPCell c1 = new PdfPCell (new Phrase("ID Barang"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c1);
                
                PdfPCell c2 = new PdfPCell (new Phrase("Nama Barang"));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c2);
                
                PdfPCell c3 = new PdfPCell (new Phrase("Spesifikasi"));
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c3);
                
                PdfPCell c4 = new PdfPCell (new Phrase("Dana"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c4);
                
                PdfPCell c5 = new PdfPCell (new Phrase("Kategori"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c5);
                
                PdfPCell c6 = new PdfPCell (new Phrase("Stok Barang"));
                c6.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c6);
                
                PdfPCell c7 = new PdfPCell (new Phrase("Tahun Pengadaan"));
                c7.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c7);
             
                while (konek.rs.next()){
                    
                    try {
                        
                        table.addCell(konek.rs.getString("id_barang"));
                        table.addCell(konek.rs.getString("nama_barang"));
                        table.addCell(konek.rs.getString("spek"));
                        table.addCell(konek.rs.getString("dana"));
                        table.addCell(konek.rs.getString("kategori"));
                        table.addCell(konek.rs.getString("stok_barang"));
                        table.addCell(konek.rs.getString("tahun"));
                    
                    }
                    catch (Exception e) {
                        
                    }
                }
                
                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan, Data tersimpan didalam project");
                
            } catch(Exception e){
                
        }
        
    }//GEN-LAST:event_btnPdf1ActionPerformed

    private void btnExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel1ActionPerformed
        // TODO add your handling code here:
        
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            
            try {
                
                TableModel tModel = tbTahun.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));
                // write header
                
                for(int i = 0; i < tModel.getColumnCount(); i++){
                    fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
                }
                fileWriter.write("\n");
                // write record
                
                for(int i=0; i < tModel.getRowCount(); i++) {
                    for(int j=0; j < tModel.getColumnCount(); j++) {
                        fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
                    }
                    fileWriter.write("\n");
                }
                fileWriter.close();
            
            } catch(Exception e){
                
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnExcel1ActionPerformed
   
    public void resetAll(){
        
        txtID.setText("");
        txtNamaBrng.setText("");
        txtSpek.setText("");
        txtInventaris.setText("");
        txtMAC.setText("");
        txtStok.setText("");
        txtDana.setText("");
        txtTahun.setText("");
        cboKategori.setSelectedIndex(0);
        
        
        masuk = (DefaultTableModel) tbInput.getModel();
        keluar = (DefaultTableModel) tbStok.getModel();
        keluar1 = (DefaultTableModel) tbTahun.getModel();
       
        int rowCount1 = masuk.getRowCount();
        int rowCount2 = keluar.getRowCount();
        int rowCount3 = keluar1.getRowCount();
        
        //Remove rows one by one from the end of the table
        
        for (int i = rowCount1 - 1; i >= 0; i--) {
            masuk.removeRow(i);
        }
        for (int i = rowCount2 - 1; i >= 0; i--) {
            keluar.removeRow(i);
        }
        for (int i = rowCount3 - 1; i >= 0; i--) {
            keluar1.removeRow(i);
        }
    }
    
    public void tampil_masuk(){
        
        masuk = (DefaultTableModel) tbInput.getModel();
        
        try {
            konek.st = konek.conn.createStatement();
            String query = "SELECT * FROM tb_peralatan";
            konek.rs = konek.st.executeQuery(query);
            while (konek.rs.next()) {
                
                String id_barang = konek.rs.getString("id_barang");
                String nama_barang = konek.rs.getString("nama_barang");
                String spek = konek.rs.getString("spek");
                String inventaris = konek.rs.getString("no_inventaris");
                String mac = konek.rs.getString("mac");
                String stok = konek.rs.getString("stok_barang");
                String dana = konek.rs.getString("dana");
                String tahun = konek.rs.getString("tahun");
                String kategori = konek.rs.getString("kategori");
                
                String [] data = {id_barang, nama_barang, spek, inventaris, mac, stok, dana, tahun, kategori};
                masuk.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data"+e);
        }
        tbInput.setModel(masuk);
    }

    
    public void tampil_keluar(){
        
       
    }
    public void tampil_keluar1(){
        
       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPeralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPeralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPeralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPeralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPeralatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnExcel1;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnPdf1;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cboKategori;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnTutup;
    private javax.swing.JTable tbInput;
    private javax.swing.JTable tbStok;
    private javax.swing.JTable tbTahun;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtCari2;
    private javax.swing.JTextField txtDana;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInventaris;
    private javax.swing.JTextField txtMAC;
    private javax.swing.JTextField txtNamaBrng;
    private javax.swing.JTextArea txtSpek;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
